# file: etcd.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: etcd
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-nodeport # Đặt tên khác để tránh xung đột với headless service cũ
  namespace: etcd
spec:
  type: NodePort  # <--- Quan trọng
  selector:
    app: etcd
  ports:
    - name: client
      port: 2379
      targetPort: 2379
      nodePort: 32379 # <--- Cổng cố định (từ 30000-32767)
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: etcd
spec:
  serviceName: etcd-service
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.6.0
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        - containerPort: 8080
          name: metrics
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command: ["/usr/local/bin/etcd"]
        args:
        - --name=$(POD_NAME)
        - --data-dir=/data
        - --enable-grpc-gateway=true
        - --listen-peer-urls=http://0.0.0.0:2380
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://$(POD_NAME).etcd-service.etcd.svc.cluster.local:2379
        - --initial-advertise-peer-urls=http://$(POD_NAME).etcd-service.etcd.svc.cluster.local:2380
        - --initial-cluster=etcd-0=http://etcd-0.etcd-service.etcd.svc.cluster.local:2380
        - --initial-cluster-state=new
        - --initial-cluster-token=etcd-etcd
        - --listen-metrics-urls=http://0.0.0.0:8080
        volumeMounts:
        - name: etcd-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi
