apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis-app
  template:
    metadata:
      labels:
        app: analysis-app
    spec:
      containers:
      - name: analysis-app
        image: my-monitor-system:v1
        imagePullPolicy: Never
        command: ["python", "app.py"]
        ports:
        - containerPort: 7860
        env:
        - name: KAFKA_BOOTSTRAP
          value: "kafka-0.kafka-service.kafka.svc.cluster.local:9092"
        - name: ETCD_HOST
          value: "etcd-0.etcd-service.etcd.svc.cluster.local"
        - name: ETCD_PORT
          value: "2379"
---
apiVersion: v1
kind: Service
metadata:
  name: analysis-service
spec:
  type: NodePort
  selector:
    app: analysis-app
  ports:
    - port: 7860
      targetPort: 7860
      nodePort: 30060 # Bạn truy cập Web qua IP_Node:30060