apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: my-monitor-system:v1
        imagePullPolicy: Never
        command: ["python", "server.py"]
        ports:
        - containerPort: 50051
        env:
        - name: KAFKA_BOOTSTRAP
          value: "kafka-service.kafka.svc.cluster.local:9092"
        - name: ETCD_HOST
          value: "etcd-service.etcd.svc.cluster.local" 
        - name: ETCD_PORT
          value: "2379"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-service
spec:
  type: NodePort
  selector:
    app: grpc-server
  ports:
    - port: 50051
      targetPort: 50051
      nodePort: 30051 # Agent sẽ kết nối vào IP_Node:30051