# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import monitoring_pb2 as monitoring__pb2


class MonitorServiceStub(object):
    """Định nghĩa service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamMetrics = channel.stream_stream(
                '/monitoring.MonitorService/StreamMetrics',
                request_serializer=monitoring__pb2.MetricMessage.SerializeToString,
                response_deserializer=monitoring__pb2.CommandMessage.FromString,
                )


class MonitorServiceServicer(object):
    """Định nghĩa service
    """

    def StreamMetrics(self, request_iterator, context):
        """Bidirectional streaming: Client gửi stream Metric, Server trả về stream Command
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamMetrics': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamMetrics,
                    request_deserializer=monitoring__pb2.MetricMessage.FromString,
                    response_serializer=monitoring__pb2.CommandMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'monitoring.MonitorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MonitorService(object):
    """Định nghĩa service
    """

    @staticmethod
    def StreamMetrics(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/monitoring.MonitorService/StreamMetrics',
            monitoring__pb2.MetricMessage.SerializeToString,
            monitoring__pb2.CommandMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
