# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitoring.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10monitoring.proto\x12\nmonitoring\"S\n\rMetricMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x0e\n\x06metric\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x02\"4\n\x0e\x43ommandMessage\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t2\\\n\x0eMonitorService\x12J\n\rStreamMetrics\x12\x19.monitoring.MetricMessage\x1a\x1a.monitoring.CommandMessage(\x01\x30\x01\x62\x06proto3')



_METRICMESSAGE = DESCRIPTOR.message_types_by_name['MetricMessage']
_COMMANDMESSAGE = DESCRIPTOR.message_types_by_name['CommandMessage']
MetricMessage = _reflection.GeneratedProtocolMessageType('MetricMessage', (_message.Message,), {
  'DESCRIPTOR' : _METRICMESSAGE,
  '__module__' : 'monitoring_pb2'
  # @@protoc_insertion_point(class_scope:monitoring.MetricMessage)
  })
_sym_db.RegisterMessage(MetricMessage)

CommandMessage = _reflection.GeneratedProtocolMessageType('CommandMessage', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDMESSAGE,
  '__module__' : 'monitoring_pb2'
  # @@protoc_insertion_point(class_scope:monitoring.CommandMessage)
  })
_sym_db.RegisterMessage(CommandMessage)

_MONITORSERVICE = DESCRIPTOR.services_by_name['MonitorService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METRICMESSAGE._serialized_start=32
  _METRICMESSAGE._serialized_end=115
  _COMMANDMESSAGE._serialized_start=117
  _COMMANDMESSAGE._serialized_end=169
  _MONITORSERVICE._serialized_start=171
  _MONITORSERVICE._serialized_end=263
# @@protoc_insertion_point(module_scope)
